admin_tools_calculator:
    resource: "@AdminToolsCalculatorBundle/Controller/"
    type:     annotation
    prefix:   /

admin_prod_product:
    resource: "@AdminProdProductBundle/Controller/"
    type:     annotation
    prefix:   /

admin_prod_dph:
    resource: "@AdminProdDphBundle/Controller/"
    type:     annotation
    prefix:   /

